import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faArrowLeft,
  faArrowRight,
  faBalanceScale,
  faBriefcase,
  faBuilding,
  faBullhorn,
  faCalendarCheck,
  faCertificate,
  faCheck,
  faCircleQuestion,
  faCopyright,
  faEnvelope,
  faFileContract,
  faFileInvoiceDollar,
  faFingerprint,
  faGavel,
  faGlobe,
  faHandshake,
  faHeadset,
  faIdCard,
  faLandmark,
  faLock,
  faMagnifyingGlass,
  faPhone,
  faReceipt,
  faRankingStar,
  faScaleBalanced,
  faShieldHalved,
  faStamp,
  faStar,
  faTrophy,
  faUser,
  faUserPlus,
  faUsers
} from "@fortawesome/free-solid-svg-icons";

const icons = {
  appointment: faCalendarCheck,
  arrowLeft: faArrowLeft,
  arrowRight: faArrowRight,
  arms: faShieldHalved,
  balance: faBalanceScale,
  building: faBuilding,
  business: faBriefcase,
  certificate: faCertificate,
  check: faCheck,
  chamber: faHandshake,
  copyright: faCopyright,
  email: faEnvelope,
  faq: faCircleQuestion,
  filing: faFileContract,
  fingerprint: faFingerprint,
  gavel: faGavel,
  globe: faGlobe,
  handshake: faHandshake,
  headset: faHeadset,
  id: faIdCard,
  landmark: faLandmark,
  labour: faUsers,
  lock: faLock,
  phone: faPhone,
  receipt: faReceipt,
  registration: faUserPlus,
  ranking: faRankingStar,
  scale: faScaleBalanced,
  search: faMagnifyingGlass,
  shield: faShieldHalved,
  stamp: faStamp,
  star: faStar,
  tax: faFileInvoiceDollar,
  trophy: faTrophy,
  trademark: faBullhorn,
  user: faUser
};

export default function FaIcon({ name, className = "" }) {
  return <FontAwesomeIcon className={className} icon={icons[name] || faScaleBalanced} />;
}
